"""Put Flieber to work (/put-flieber-to-work): the single source of example prompts for the site.

Built from the "Prompt Examples" in 26-05-29 AI Lab - Product Strategy and the prompts already on the site
(Content Briefing section 15). Entries with custom=True are not out of the box: they work once the customer
connects the right sources through Flieber's MCP client (Fabricio, Oct 5), and carry a "Requires custom
configuration" note.
"""

PAGE = {
    "slug": "put-flieber-to-work", "name": "Put Flieber to work",
    "h1": "Put Flieber to work on your operation",
    "lead": ("Ask a question, test a decision or hand off a recurring job, in plain language, in the Flieber app, in "
             "Slack or in Claude, ChatGPT or any MCP-compatible agent. These are the jobs operators give Flieber today, "
             "what Flieber does with each one and what comes back."),
    "note": ("Some of these need a connection or a workflow set up for your account. On a demo we'll show which ones run "
             "on your setup today."),
    "close_h2": "Try these on your own data",
    "close_body": "Start a 14-day free trial, connect your channels and ask your first question in minutes.",
    "more": "More ways to put Flieber to work",
    "custom_label": "Requires custom configuration",
    "custom_note": "Connect the right sources through Flieber's MCP client; not available out of the box.",
}

GROUPS = [
    ("daily", "Daily risks and reviews"), ("purchasing", "Purchasing"), ("forecasting", "Forecasting and launches"),
    ("locations", "Stock across locations"), ("promotions", "Promotions and ads"), ("suppliers", "Suppliers and inbound"),
    ("overstock", "Overstock and cash"), ("wholesale", "Wholesale and bundles"), ("data", "Data quality"),
]
SCHEDULE = {"once": "Runs once", "scheduled": "Runs on schedule"}
APPROVAL = {"read_only": "Read only", "asks_first": "Asks before changing anything", "after_approval": "Changes after your approval"}

DL, DF, IF, RP, WF = "data-layer", "demand-forecasting", "inventory-forecasting", "replenishment", "workflows"
ALL = [DL, DF, IF, RP, WF]

def E(i, group, title, modules, schedule, approval, prompt, does, gets, connections=(), custom=False):
    return {"id": f"p{i}", "n": i, "group": group, "title": title, "modules": modules, "schedule": schedule,
            "approval": approval, "prompt": prompt, "does": does, "gets": gets, "connections": list(connections),
            "custom": custom}

ENTRIES = [
    E(1, "daily", "Morning risk review", [IF, WF], "scheduled", "read_only",
      "Every morning, review my inventory position and tell me the biggest risks I need to act on. Prioritize by stockout risk, sales velocity, product tier, inbound shipments and revenue impact, and explain why each one matters.",
      "Projects stock for every product and location, ranks the risks by the criteria you named and explains each one.",
      "A short list of products to act on, with the reason and a recommended next step, every morning in the app or Slack."),
    E(2, "daily", "Weekly operations memo", ALL, "scheduled", "read_only",
      "Every Monday, prepare an inventory operations memo. Combine Flieber data with supplier emails, freight updates and major forecast exceptions. Tell me the top risks, what changed and what decisions need to be made.",
      "Gathers the week's changes in stock, forecasts and inbound shipments, reads connected supplier emails and ranks what needs a decision.",
      "One memo every Monday with the risks, the changes and the decisions waiting for you.", ["Gmail or Outlook"]),
    E(3, "daily", "Monthly inventory health", [IF, DL], "scheduled", "read_only",
      "Every month, review our overall inventory health and explain what changed. Tell me whether we are carrying too much or too little inventory, where the biggest working capital issues are and what we should prioritize.",
      "Compares inventory value, coverage, overstock and stockouts with the previous month and finds the products driving the change.",
      "A monthly summary of inventory health with the working capital at stake and the actions to prioritize."),
    E(4, "daily", "Amazon stockouts before the next PO", [IF], "once", "read_only",
      "Which of our top SKUs run out on Amazon before their next purchase order lands?",
      "Projects Amazon stock for your top products and compares each stockout date with the arrival of open POs and inbound shipments.",
      "The products that will run out first, by how many days, and the options to cover the gap."),
    E(5, "purchasing", "Weekly replenishment", [RP], "scheduled", "read_only",
      "Every Monday, review the products that may need replenishment and recommend what to order. Consider current stock, forecast demand, on-order inventory, supplier lead time, MOQ and target coverage. Group the recommendations by supplier and explain the reasoning.",
      "Runs replenishment for every product and location with your planning parameters and order constraints applied.",
      "Recommended orders grouped by supplier, each with the reasoning behind the quantity."),
    E(6, "purchasing", "Draft POs and send them to your ERP", [RP, WF], "scheduled", "after_approval",
      "Every Monday, draft POs by supplier and send them to NetSuite for approval.",
      "Drafts purchase orders by supplier and date, with costs, and once you approve, pushes them into your ERP.",
      "Draft POs ready for review every Monday; nothing reaches the ERP until you approve.", ["NetSuite, Cin7 or Brightpearl"]),
    E(7, "purchasing", "Container fill", [RP], "once", "read_only",
      "Fit this order into two 40-foot containers.",
      "Rebalances the planned quantities to fit container capacity, with case packs and MOQs still applied.",
      "An adjusted order that fills the containers, with what changed and why."),
    E(8, "purchasing", "Six months of buying within budget", [RP], "once", "read_only",
      "Plan the next six months of orders from this supplier within our budget.",
      "Splits the buying horizon into seasonally weighted purchase orders, applies cartons, MOQs and lead times and keeps the total within your budget and cash-flow limits.",
      "A month-by-month purchase plan for that supplier."),
    E(9, "purchasing", "Lead time scenario", [RP], "once", "read_only",
      "What if lead times slip by two weeks?",
      "Simulates the longer lead time and recalculates inventory, stockouts, revenue, margin and cash.",
      "The products that would run out, the sales at stake and what to order earlier."),
    E(10, "purchasing", "Send a PO to the supplier", [WF], "once", "after_approval",
      "Email this PO to the supplier once I approve it.",
      "Prepares the PO in the supplier's own format, as an email, CSV file or Google Sheet, and sends it once you approve.",
      "The PO in the supplier's inbox, with the send recorded in Flieber."),
    E(11, "forecasting", "Forecasts that look wrong", [DF], "scheduled", "read_only",
      "Review my forecast every week and flag products where it looks wrong: new products with little history, products affected by stockouts, sudden accelerations, discontinued products still showing demand and products where actual sales are consistently above or below forecast.",
      "Checks every forecast against these patterns and against actual sales.",
      "A weekly list of forecasts to review, with the reason each one was flagged."),
    E(12, "forecasting", "Why actuals and forecast differ", [DF], "once", "read_only",
      "When actual sales and forecast are far apart, investigate why. Check recent stockouts, promotions, ad spend changes, new product status and seasonality before recommending whether the forecast should change.",
      "Compares actual sales with the forecast and checks each likely cause in your data and connected apps.",
      "The most likely reason for the gap and a recommendation to keep or change the forecast."),
    E(13, "forecasting", "New launches", [DF, RP], "scheduled", "read_only",
      "Compare new launches with similar past launches at 7, 14 and 30 days and tell me whether to reorder earlier.",
      "Compares each launch's early sales with similar past launches and updates the expected sales pace.",
      "Which launches are over or under pace and whether to reorder earlier than planned."),
    E(14, "forecasting", "Bundle demand", [DF, DL], "once", "read_only",
      "What will the holiday bundle sell in Q4 if we keep it in stock?",
      "Forecasts the bundle from history adjusted for past stockouts and converts the demand into components.",
      "The Q4 forecast for the bundle and what it means for each component."),
    E(15, "forecasting", "Forecast accuracy", [DF], "once", "read_only",
      "How accurate was last quarter's forecast?",
      "Compares saved forecast versions with what actually sold.",
      "Error and bias by product, channel or group, and where the forecast was furthest off."),
    E(16, "locations", "Transfers between locations", [RP], "scheduled", "read_only",
      "Recommend transfers when one location is about to stock out and another has excess, without creating a new risk at the origin.",
      "Projects stock at every location and checks the origin before recommending any transfer.",
      "Transfers by product, from and to, with the stockout each one prevents."),
    E(17, "locations", "FBA inbound shipment", [WF], "once", "after_approval",
      "Create the FBA inbound shipment for this plan.",
      "Creates the inbound shipment in Amazon from the approved plan and tracks it to delivery.",
      "The shipment created in Seller Central and visible in Flieber."),
    E(18, "locations", "Regional demand from one store", [DL, IF], "once", "read_only",
      "Split last week's Shopify orders by region and show what each warehouse needs to cover the next 30 days.",
      "Routes orders to the regions or warehouses you set and projects each location's needs.",
      "Units needed by warehouse and product for the next 30 days."),
    E(19, "locations", "Inventory that doesn't match", [DL], "scheduled", "read_only",
      "Compare inventory levels between Flieber, Shopify, Amazon and our 3PL every morning. If numbers don't match, investigate the likely reason and tell me which system to trust.",
      "Compares balances across connected systems and investigates each mismatch.",
      "A daily list of mismatches with the likely cause and the system to trust.", custom=True),
    E(20, "promotions", "Stock check before a promotion", [IF], "scheduled", "read_only",
      "Before every promotion, check whether the promoted products have enough stock for the expected lift. If not, recommend whether to transfer inventory, reduce ad spend, delay the campaign or place an urgent PO.",
      "Projects stock for the promoted products with the expected lift and tests each option.",
      "Products at risk before the promotion starts, with the recommended fix."),
    E(21, "promotions", "Ad spend on products about to run out", [WF], "scheduled", "read_only",
      "Alert the marketing team in Slack when ad spend rises on a SKU projected to stock out within 30 days.",
      "Watches ad spend in connected ad accounts against projected stockouts.",
      "A Slack alert with the SKU, the stockout date and the spend at risk.", ["Meta Ads, Google Ads"]),
    E(22, "promotions", "Ads and cash", [RP], "once", "read_only",
      "If we pause ads on the five SKUs most at risk of stocking out, what happens to cash in November?",
      "Simulates the lower demand and recalculates inventory, revenue and cash.",
      "The revenue given up, the stockouts avoided and the cash freed."),
    E(23, "promotions", "Act on forecasted stockouts", [WF], "scheduled", "asks_first",
      "When a product has a forecasted stockout, adjust price and ad campaigns accordingly.",
      "Watches projected stockouts and prepares price and campaign changes in the connected systems.",
      "Proposed changes for approval; with your rules, they can run on their own.", ["Ad accounts or pricing system with an MCP server"]),
    E(24, "suppliers", "Supplier emails update POs", [WF], "scheduled", "after_approval",
      "Watch supplier emails about open POs. When a supplier confirms a new delivery date, quantity or split shipment, compare it with the PO in Flieber and ask me before updating it.",
      "Reads connected supplier emails, matches them to open POs and prepares the update.",
      "PO changes waiting for your approval instead of buried in your inbox.", ["Gmail or Outlook"]),
    E(25, "suppliers", "Late POs that cause stockouts", [WF, IF], "scheduled", "read_only",
      "Tell me when any open PO is at risk of arriving late. If the delay may cause a stockout, show the affected SKUs, the expected stockout date and the recommended action.",
      "Tracks open POs and supplier updates and recalculates stock when an arrival moves.",
      "An alert only when a delay matters, with what to do about it.", ["Gmail or Outlook"]),
    E(26, "suppliers", "Supplier behavior", [WF], "scheduled", "read_only",
      "Track which suppliers are repeatedly late, short-shipping or changing quantities.",
      "Reviews PO and shipment history and supplier emails for each supplier.",
      "A supplier scorecard with the patterns that affect your plan.", ["Gmail or Outlook"]),
    E(27, "suppliers", "Freight ETA changes", [WF], "scheduled", "after_approval",
      "When a freight forwarder or carrier updates an ETA, update the shipment in Flieber and recalculate whether any destination will stock out before arrival.",
      "Reads forwarder and carrier updates, matches them to inbound shipments and recalculates stock at each destination.",
      "Shipment dates kept current, with an alert when a new ETA causes a stockout.", custom=True),
    E(28, "suppliers", "3PL receiving check", [WF], "scheduled", "after_approval",
      "Every day, compare our 3PL receiving reports with expected inbound shipments. If fewer units arrived than expected, flag it and update the received quantity only after my approval.",
      "Compares what the 3PL received with what was expected on each inbound shipment.",
      "A daily list of short receipts, with the corrected quantities waiting for your approval.", custom=True),
    E(29, "suppliers", "Landed cost changes", [WF], "scheduled", "read_only",
      "Compare supplier and freight invoices with PO costs and tell me which SKUs had landed cost changes that materially affect margin.",
      "Matches invoices to POs and recalculates landed cost by SKU.",
      "The SKUs whose landed cost changed, by how much and the effect on margin.", custom=True),
    E(30, "overstock", "What to do with overstock", [IF], "once", "read_only",
      "Review my overstocked products and recommend what to do with each one: keep, discount, bundle, transfer, pause replenishment or liquidate. Consider sales velocity, margin, product tier, seasonality and inventory value.",
      "Finds excess inventory by product and location and weighs each option against the criteria you named.",
      "A recommendation per product, with the inventory value at stake."),
    E(31, "overstock", "The cost of stockouts", [IF], "once", "read_only",
      "What did stockouts cost us last month?",
      "Estimates the sales lost to unavailable stock, by product and channel.",
      "Lost sales in units and revenue, and the products that cost the most."),
    E(32, "wholesale", "Large wholesale orders", [IF, RP], "scheduled", "read_only",
      "When a large wholesale order comes in, check whether fulfilling it puts DTC or Amazon stock at risk and recommend whether to accept, split, delay or replenish.",
      "Counts the order as allocated stock and projects every channel with and without it.",
      "The channels put at risk and the recommended response.", ["Gmail or Outlook, or SPS Commerce"]),
    E(33, "wholesale", "Components that block bundles", [DL, RP], "scheduled", "read_only",
      "Tell me if any component will stop us from assembling finished goods or bundles in the next 60 days.",
      "Converts bundle demand into components and projects each component's stock.",
      "The components that will run short, when and which bundles they block."),
    E(34, "data", "Weekly data check", [DL], "scheduled", "read_only",
      "Review my catalog and inventory data weekly and tell me if anything looks wrong: missing product names, discontinued products with a forecast, active products with no sales, SKUs mapped incorrectly or inbound shipments not reflected correctly.",
      "Runs data health checks across catalog, mappings, forecasts and shipments.",
      "A list of issues, with the fixes Flieber can apply and the ones that need a person."),
    E(35, "data", "Stock counted twice", [DL, WF], "scheduled", "read_only",
      "If inventory increases in a way that matches an open PO or inbound shipment, check whether the PO was marked as received. If it's still open, alert me before the same stock is counted twice.",
      "Compares balance changes with open POs and inbound shipments at each location.",
      "An alert for each PO that may be double counted, and for receipts that never reached the balance."),
    E(36, "data", "Amazon availability issues", [DL], "scheduled", "read_only",
      "Watch Seller Central for stranded inventory, suppressed listings, FBA receiving delays and restock limits, and tell me which problems are Amazon availability issues rather than real stock shortages.",
      "Checks Amazon inventory and listing status against your stock in Flieber.",
      "Each Amazon issue labeled as an availability problem or a real shortage, with the next step.", custom=True),
]
BY_ID = {e["id"]: e for e in ENTRIES}

# Where other pages pull their prompts from (draft 15.5)
HOME = ["p4", "p14", "p22", "p6", "p32", "p23"]
FEATURES = ["p1", "p5", "p11", "p16", "p20", "p13", "p30", "p24", "p21", "p32", "p26", "p2"]
MCP_BY_MODULE = {DL: ["p34", "p18", "p35"], DF: ["p11", "p15", "p14"], IF: ["p4", "p31", "p30"],
                 RP: ["p5", "p7", "p9"], WF: ["p17", "p10", "p21"]}
USE_CASES = {"amazon-fba-replenishment": ["p4", "p17"], "claude-amazon-shopify-inventory": ["p4", "p18"],
             "shopify-inventory-forecasting": ["p18", "p11"], "kits-and-bundles": ["p14", "p33"],
             "wholesale-edi-demand-planning": ["p32", "p11"], "multi-warehouse-3pl-inventory": ["p16", "p18"],
             "purchase-order-automation": ["p6", "p10"], "ai-demand-forecasting": ["p11", "p31"],
             "moq-container-planning": ["p7", "p8"], "backorders-preorders": ["p5", "p4"]}
